import type { ModelEntry } from "./model-types";

// Static model data sourced from:
// - https://github.com/cheahjs/free-llm-api-resources
// - https://github.com/mnfst/awesome-free-llm-apis
// - https://freellm.net

const groq: ModelEntry[] = [
  { id: "groq/llama-3.3-70b-versatile", name: "Llama 3.3 70B Versatile", description: "Meta's Llama 3.3 70B — strong general-purpose model with 131K context. Groq's ultra-fast LPU inference.", contextLength: 131072, modality: "Text", provider: "groq", providerDisplay: "Groq", providerUrl: "https://groq.com", modelUrl: "https://console.groq.com/docs/models", source: "groq", requiresKey: true, signupUrl: "https://console.groq.com/keys", rateLimits: "30 RPM · 14,400 RPD", createdAt: 0 },
  { id: "groq/llama-3.1-8b-instant", name: "Llama 3.1 8B Instant", description: "Blazing fast 8B model with 131K context. Great for latency-sensitive tasks.", contextLength: 131072, modality: "Text", provider: "groq", providerDisplay: "Groq", providerUrl: "https://groq.com", modelUrl: "https://console.groq.com/docs/models", source: "groq", requiresKey: true, signupUrl: "https://console.groq.com/keys", rateLimits: "30 RPM · 14,400 RPD", createdAt: 0 },
  { id: "groq/llama-4-scout-17b-16e-instruct", name: "Llama 4 Scout 17B (16E)", description: "Meta's multimodal Llama 4 Scout with vision support. 131K context.", contextLength: 131072, modality: "Multimodal (Vision)", provider: "groq", providerDisplay: "Groq", providerUrl: "https://groq.com", modelUrl: "https://console.groq.com/docs/models", source: "groq", requiresKey: true, signupUrl: "https://console.groq.com/keys", rateLimits: "30 RPM · 14,400 RPD", createdAt: 0 },
  { id: "groq/llama-4-maverick-17b-128e-instruct", name: "Llama 4 Maverick 17B (128E)", description: "Meta's Llama 4 Maverick with multimodal vision. Higher capability than Scout.", contextLength: 131072, modality: "Multimodal (Vision)", provider: "groq", providerDisplay: "Groq", providerUrl: "https://groq.com", modelUrl: "https://console.groq.com/docs/models", source: "groq", requiresKey: true, signupUrl: "https://console.groq.com/keys", rateLimits: "15 RPM · 500 RPD", createdAt: 0 },
  { id: "groq/qwen3-32b", name: "Qwen3 32B", description: "Alibaba's Qwen3 32B with 131K context on Groq's fast inference hardware.", contextLength: 131072, modality: "Text", provider: "groq", providerDisplay: "Groq", providerUrl: "https://groq.com", modelUrl: "https://console.groq.com/docs/models", source: "groq", requiresKey: true, signupUrl: "https://console.groq.com/keys", rateLimits: "30 RPM · 14,400 RPD", createdAt: 0 },
  { id: "groq/gpt-oss-120b", name: "GPT-OSS 120B", description: "OpenAI's open-source 120B model hosted on Groq for ultra-fast inference.", contextLength: 131072, modality: "Text", provider: "groq", providerDisplay: "Groq", providerUrl: "https://groq.com", modelUrl: "https://console.groq.com/docs/models", source: "groq", requiresKey: true, signupUrl: "https://console.groq.com/keys", rateLimits: "30 RPM · 14,400 RPD", createdAt: 0 },
  { id: "groq/kimi-k2-instruct", name: "Kimi K2 Instruct", description: "Moonshot AI's Kimi K2 with 262K context. Strong agentic and coding capabilities.", contextLength: 262144, modality: "Text", provider: "groq", providerDisplay: "Groq", providerUrl: "https://groq.com", modelUrl: "https://console.groq.com/docs/models", source: "groq", requiresKey: true, signupUrl: "https://console.groq.com/keys", rateLimits: "30 RPM · 14,400 RPD", createdAt: 0 },
  { id: "groq/deepseek-r1-distill-70b", name: "DeepSeek R1 Distill 70B", description: "DeepSeek R1 distilled into 70B — chain-of-thought reasoning at speed.", contextLength: 131072, modality: "Text", provider: "groq", providerDisplay: "Groq", providerUrl: "https://groq.com", modelUrl: "https://console.groq.com/docs/models", source: "groq", requiresKey: true, signupUrl: "https://console.groq.com/keys", rateLimits: "30 RPM · 14,400 RPD", createdAt: 0 },
];

const google: ModelEntry[] = [
  { id: "google/gemini-2.5-pro", name: "Gemini 2.5 Pro", description: "Google's most capable model with 2M context. Text, image, audio, and video input.", contextLength: 2097152, modality: "Multimodal (Vision)", provider: "google", providerDisplay: "Google AI Studio", providerUrl: "https://ai.google.dev", modelUrl: "https://aistudio.google.com", source: "google", requiresKey: true, signupUrl: "https://aistudio.google.com", rateLimits: "5 RPM · 100 RPD", notes: "Not available in EU/UK/Switzerland. Prompts may be used for training.", createdAt: 0 },
  { id: "google/gemini-2.5-flash", name: "Gemini 2.5 Flash", description: "Fast multimodal model with 1M context. Handles text, image, audio, and video.", contextLength: 1048576, modality: "Multimodal (Vision)", provider: "google", providerDisplay: "Google AI Studio", providerUrl: "https://ai.google.dev", modelUrl: "https://aistudio.google.com", source: "google", requiresKey: true, signupUrl: "https://aistudio.google.com", rateLimits: "10 RPM · 250 RPD", notes: "Not available in EU/UK/Switzerland.", createdAt: 0 },
  { id: "google/gemini-2.5-flash-lite", name: "Gemini 2.5 Flash-Lite", description: "Lightweight Gemini 2.5 Flash with 1M context and higher rate limits.", contextLength: 1048576, modality: "Multimodal (Vision)", provider: "google", providerDisplay: "Google AI Studio", providerUrl: "https://ai.google.dev", modelUrl: "https://aistudio.google.com", source: "google", requiresKey: true, signupUrl: "https://aistudio.google.com", rateLimits: "15 RPM · 1,000 RPD", createdAt: 0 },
  { id: "google/gemma-3-27b-it", name: "Gemma 3 27B Instruct", description: "Google's open Gemma 3 model at 27B parameters. Strong general capabilities.", contextLength: 131072, modality: "Text", provider: "google", providerDisplay: "Google AI Studio", providerUrl: "https://ai.google.dev", modelUrl: "https://aistudio.google.com", source: "google", requiresKey: true, signupUrl: "https://aistudio.google.com", rateLimits: "30 RPM · 14,400 RPD", createdAt: 0 },
  { id: "google/gemma-3-12b-it", name: "Gemma 3 12B Instruct", description: "Google's open Gemma 3 model at 12B parameters.", contextLength: 131072, modality: "Text", provider: "google", providerDisplay: "Google AI Studio", providerUrl: "https://ai.google.dev", modelUrl: "https://aistudio.google.com", source: "google", requiresKey: true, signupUrl: "https://aistudio.google.com", rateLimits: "30 RPM · 14,400 RPD", createdAt: 0 },
  { id: "google/gemma-3-4b-it", name: "Gemma 3 4B Instruct", description: "Compact Gemma 3 at 4B — efficient for on-device and high-throughput workloads.", contextLength: 131072, modality: "Text", provider: "google", providerDisplay: "Google AI Studio", providerUrl: "https://ai.google.dev", modelUrl: "https://aistudio.google.com", source: "google", requiresKey: true, signupUrl: "https://aistudio.google.com", rateLimits: "30 RPM · 14,400 RPD", createdAt: 0 },
];

const cerebras: ModelEntry[] = [
  { id: "cerebras/llama-3.3-70b", name: "Llama 3.3 70B", description: "Meta's Llama 3.3 70B on Cerebras wafer-scale silicon. ~2,600 tokens/sec inference.", contextLength: 8192, modality: "Text", provider: "cerebras", providerDisplay: "Cerebras", providerUrl: "https://cerebras.ai", modelUrl: "https://cloud.cerebras.ai", source: "cerebras", requiresKey: true, signupUrl: "https://cloud.cerebras.ai", rateLimits: "30 RPM · 14,400 RPD · 1M TPD", notes: "Context capped at 8K on free tier.", createdAt: 0 },
  { id: "cerebras/gpt-oss-120b", name: "GPT-OSS 120B", description: "OpenAI's 120B OSS model on the world's fastest inference hardware.", contextLength: 8192, modality: "Text", provider: "cerebras", providerDisplay: "Cerebras", providerUrl: "https://cerebras.ai", modelUrl: "https://cloud.cerebras.ai", source: "cerebras", requiresKey: true, signupUrl: "https://cloud.cerebras.ai", rateLimits: "30 RPM · 14,400 RPD · 1M TPD", notes: "Context capped at 8K on free tier.", createdAt: 0 },
  { id: "cerebras/qwen-3-235b-a22b", name: "Qwen3 235B (A22B)", description: "Alibaba's massive 235B MoE model at extreme speed via Cerebras hardware.", contextLength: 8192, modality: "Text", provider: "cerebras", providerDisplay: "Cerebras", providerUrl: "https://cerebras.ai", modelUrl: "https://cloud.cerebras.ai", source: "cerebras", requiresKey: true, signupUrl: "https://cloud.cerebras.ai", rateLimits: "30 RPM · 14,400 RPD · 1M TPD", notes: "Context capped at 8K on free tier.", createdAt: 0 },
  { id: "cerebras/llama-4-scout-17b", name: "Llama 4 Scout 17B", description: "Meta's multimodal Llama 4 Scout with vision on Cerebras ultra-fast inference.", contextLength: 8192, modality: "Multimodal (Vision)", provider: "cerebras", providerDisplay: "Cerebras", providerUrl: "https://cerebras.ai", modelUrl: "https://cloud.cerebras.ai", source: "cerebras", requiresKey: true, signupUrl: "https://cloud.cerebras.ai", rateLimits: "30 RPM · 14,400 RPD · 1M TPD", notes: "Context capped at 8K on free tier.", createdAt: 0 },
];

const nvidia: ModelEntry[] = [
  { id: "nvidia/deepseek-ai/deepseek-r1", name: "DeepSeek R1", description: "Full DeepSeek R1 with extended chain-of-thought reasoning. 128K context.", contextLength: 131072, modality: "Text", provider: "nvidia", providerDisplay: "NVIDIA NIM", providerUrl: "https://build.nvidia.com", modelUrl: "https://build.nvidia.com/deepseek-ai/deepseek-r1", source: "nvidia", requiresKey: true, signupUrl: "https://build.nvidia.com", rateLimits: "~40 RPM", notes: "Phone number verification required.", createdAt: 0 },
  { id: "nvidia/llama-3.1-nemotron-ultra-253b", name: "Llama 3.1 Nemotron Ultra 253B", description: "NVIDIA's post-trained Nemotron Ultra at 253B. Top-tier reasoning and instruction following.", contextLength: 131072, modality: "Text", provider: "nvidia", providerDisplay: "NVIDIA NIM", providerUrl: "https://build.nvidia.com", modelUrl: "https://build.nvidia.com/nvidia/llama-3_1-nemotron-ultra-253b-v1", source: "nvidia", requiresKey: true, signupUrl: "https://build.nvidia.com", rateLimits: "~40 RPM", notes: "Phone number verification required.", createdAt: 0 },
  { id: "nvidia/nemotron-3-super-120b", name: "Nemotron 3 Super 120B", description: "NVIDIA's efficient 120B sparse MoE model with 262K context.", contextLength: 262144, modality: "Text", provider: "nvidia", providerDisplay: "NVIDIA NIM", providerUrl: "https://build.nvidia.com", modelUrl: "https://build.nvidia.com/nvidia/nemotron-3-super-120b-a12b", source: "nvidia", requiresKey: true, signupUrl: "https://build.nvidia.com", rateLimits: "~40 RPM", notes: "Phone number verification required.", createdAt: 0 },
  { id: "nvidia/meta/llama-3.1-405b-instruct", name: "Llama 3.1 405B Instruct", description: "Meta's flagship 405B model. One of the strongest open-weight models available.", contextLength: 131072, modality: "Text", provider: "nvidia", providerDisplay: "NVIDIA NIM", providerUrl: "https://build.nvidia.com", modelUrl: "https://build.nvidia.com/meta/llama-3_1-405b-instruct", source: "nvidia", requiresKey: true, signupUrl: "https://build.nvidia.com", rateLimits: "~40 RPM", notes: "Phone number verification required.", createdAt: 0 },
  { id: "nvidia/qwen/qwen2.5-72b-instruct", name: "Qwen 2.5 72B Instruct", description: "Alibaba's Qwen 2.5 at 72B on NVIDIA NIM. Strong coding and reasoning.", contextLength: 131072, modality: "Text", provider: "nvidia", providerDisplay: "NVIDIA NIM", providerUrl: "https://build.nvidia.com", modelUrl: "https://build.nvidia.com/qwen/qwen2.5-72b-instruct", source: "nvidia", requiresKey: true, signupUrl: "https://build.nvidia.com", rateLimits: "~40 RPM", notes: "Phone number verification required.", createdAt: 0 },
];

const github: ModelEntry[] = [
  { id: "github/openai/gpt-5", name: "GPT-5", description: "OpenAI's GPT-5 available via GitHub Models for free prototyping.", contextLength: 200000, modality: "Text", provider: "github", providerDisplay: "GitHub Models", providerUrl: "https://github.com/marketplace/models", modelUrl: "https://github.com/marketplace/models/openai/gpt-5", source: "github", requiresKey: true, signupUrl: "https://github.com/marketplace/models", rateLimits: "10 RPM · 50 RPD", notes: "Requires GitHub account. Higher limits with Copilot subscription.", createdAt: 0 },
  { id: "github/openai/gpt-4.1", name: "GPT-4.1", description: "OpenAI's GPT-4.1 with 1M context. Strong instruction following and coding.", contextLength: 1000000, modality: "Text", provider: "github", providerDisplay: "GitHub Models", providerUrl: "https://github.com/marketplace/models", modelUrl: "https://github.com/marketplace/models/openai/gpt-4.1", source: "github", requiresKey: true, signupUrl: "https://github.com/marketplace/models", rateLimits: "10 RPM · 50 RPD", notes: "Requires GitHub account. Higher limits with Copilot subscription.", createdAt: 0 },
  { id: "github/openai/gpt-4o", name: "GPT-4o", description: "OpenAI's multimodal GPT-4o with vision and broad capabilities.", contextLength: 128000, modality: "Multimodal (Vision)", provider: "github", providerDisplay: "GitHub Models", providerUrl: "https://github.com/marketplace/models", modelUrl: "https://github.com/marketplace/models/openai/gpt-4o", source: "github", requiresKey: true, signupUrl: "https://github.com/marketplace/models", rateLimits: "10 RPM · 50 RPD", notes: "Requires GitHub account.", createdAt: 0 },
  { id: "github/openai/o4-mini", name: "o4-mini", description: "OpenAI's compact reasoning model — extended thinking at lower cost.", contextLength: 200000, modality: "Text", provider: "github", providerDisplay: "GitHub Models", providerUrl: "https://github.com/marketplace/models", modelUrl: "https://github.com/marketplace/models/openai/o4-mini", source: "github", requiresKey: true, signupUrl: "https://github.com/marketplace/models", rateLimits: "10 RPM · 50 RPD", notes: "Requires GitHub account.", createdAt: 0 },
  { id: "github/meta-llama/llama-4-scout", name: "Llama 4 Scout 17B", description: "Meta's multimodal Llama 4 Scout with 512K context via GitHub Models.", contextLength: 524288, modality: "Multimodal (Vision)", provider: "github", providerDisplay: "GitHub Models", providerUrl: "https://github.com/marketplace/models", modelUrl: "https://github.com/marketplace/models", source: "github", requiresKey: true, signupUrl: "https://github.com/marketplace/models", rateLimits: "15 RPM · 150 RPD", notes: "Requires GitHub account.", createdAt: 0 },
  { id: "github/deepseek/deepseek-r1", name: "DeepSeek R1", description: "DeepSeek R1 chain-of-thought reasoning model available via GitHub Models.", contextLength: 65536, modality: "Text", provider: "github", providerDisplay: "GitHub Models", providerUrl: "https://github.com/marketplace/models", modelUrl: "https://github.com/marketplace/models", source: "github", requiresKey: true, signupUrl: "https://github.com/marketplace/models", rateLimits: "15 RPM · 150 RPD", notes: "Requires GitHub account.", createdAt: 0 },
  { id: "github/meta-llama/llama-3.3-70b", name: "Llama 3.3 70B Instruct", description: "Meta's Llama 3.3 70B on GitHub Models. 131K context.", contextLength: 131072, modality: "Text", provider: "github", providerDisplay: "GitHub Models", providerUrl: "https://github.com/marketplace/models", modelUrl: "https://github.com/marketplace/models", source: "github", requiresKey: true, signupUrl: "https://github.com/marketplace/models", rateLimits: "15 RPM · 150 RPD", notes: "Requires GitHub account.", createdAt: 0 },
];

const mistral: ModelEntry[] = [
  { id: "mistral/codestral-2501", name: "Codestral 2501", description: "Mistral's dedicated code model. 256K context, strong FIM support.", contextLength: 262144, modality: "Text", provider: "mistral", providerDisplay: "Mistral", providerUrl: "https://mistral.ai", modelUrl: "https://codestral.mistral.ai", source: "mistral", requiresKey: true, signupUrl: "https://console.mistral.ai", rateLimits: "30 RPM · 2,000 RPD", notes: "Free via Codestral endpoint. Phone verification required.", createdAt: 0 },
  { id: "mistral/mistral-small-3.1", name: "Mistral Small 3.1", description: "Efficient Mistral Small 3.1 with multimodal vision. Free on La Plateforme.", contextLength: 131072, modality: "Multimodal (Vision)", provider: "mistral", providerDisplay: "Mistral", providerUrl: "https://mistral.ai", modelUrl: "https://console.mistral.ai", source: "mistral", requiresKey: true, signupUrl: "https://console.mistral.ai", rateLimits: "1 RPS · 500K TPM", notes: "Free Experiment plan requires data training opt-in. Phone verification required.", createdAt: 0 },
  { id: "mistral/devstral-small", name: "Devstral Small", description: "Mistral's agentic coding model. Excellent for multi-file code agents.", contextLength: 131072, modality: "Text", provider: "mistral", providerDisplay: "Mistral", providerUrl: "https://mistral.ai", modelUrl: "https://console.mistral.ai", source: "mistral", requiresKey: true, signupUrl: "https://console.mistral.ai", rateLimits: "1 RPS · 500K TPM", notes: "Free Experiment plan requires data training opt-in.", createdAt: 0 },
];

const cohere: ModelEntry[] = [
  { id: "cohere/command-a-03-2025", name: "Command A", description: "Cohere's flagship Command A at 111B. 256K context, strong reasoning and RAG.", contextLength: 262144, modality: "Text", provider: "cohere", providerDisplay: "Cohere", providerUrl: "https://cohere.com", modelUrl: "https://docs.cohere.com/docs/command-r-plus", source: "cohere", requiresKey: true, signupUrl: "https://dashboard.cohere.com", rateLimits: "20 RPM · 1,000 req/month", notes: "Trial key — non-commercial use only. Shared monthly quota across models.", createdAt: 0 },
  { id: "cohere/command-r-plus-08-2024", name: "Command R+", description: "Cohere's Command R+ optimized for RAG and tool use. 128K context.", contextLength: 131072, modality: "Text", provider: "cohere", providerDisplay: "Cohere", providerUrl: "https://cohere.com", modelUrl: "https://docs.cohere.com/docs/command-r-plus", source: "cohere", requiresKey: true, signupUrl: "https://dashboard.cohere.com", rateLimits: "20 RPM · 1,000 req/month", notes: "Trial key — non-commercial use only.", createdAt: 0 },
  { id: "cohere/command-r-08-2024", name: "Command R", description: "Cohere's efficient Command R model for retrieval-augmented generation.", contextLength: 131072, modality: "Text", provider: "cohere", providerDisplay: "Cohere", providerUrl: "https://cohere.com", modelUrl: "https://docs.cohere.com/docs/command-r", source: "cohere", requiresKey: true, signupUrl: "https://dashboard.cohere.com", rateLimits: "20 RPM · 1,000 req/month", notes: "Trial key — non-commercial use only.", createdAt: 0 },
  { id: "cohere/c4ai-aya-expanse-32b", name: "Aya Expanse 32B", description: "Cohere's multilingual Aya Expanse at 32B. Supports 23+ languages.", contextLength: 131072, modality: "Text", provider: "cohere", providerDisplay: "Cohere", providerUrl: "https://cohere.com", modelUrl: "https://cohere.com/blog/aya-expanse", source: "cohere", requiresKey: true, signupUrl: "https://dashboard.cohere.com", rateLimits: "20 RPM · 1,000 req/month", notes: "Trial key — non-commercial use only.", createdAt: 0 },
];

const cloudflare: ModelEntry[] = [
  { id: "cloudflare/@cf/meta/llama-3.3-70b-instruct-fp8-fast", name: "Llama 3.3 70B Instruct (Fast)", description: "Meta's Llama 3.3 70B at the edge via Cloudflare Workers AI. 131K context.", contextLength: 131072, modality: "Text", provider: "cloudflare", providerDisplay: "Cloudflare AI", providerUrl: "https://developers.cloudflare.com/workers-ai", modelUrl: "https://developers.cloudflare.com/workers-ai/models/llama-3.3-70b-instruct-fp8-fast/", source: "cloudflare", requiresKey: true, signupUrl: "https://dash.cloudflare.com", rateLimits: "10K neurons/day (shared)", createdAt: 0 },
  { id: "cloudflare/@cf/meta/llama-4-scout-17b-16e-instruct", name: "Llama 4 Scout 17B", description: "Meta's Llama 4 Scout at the edge. Up to 10M context token support.", contextLength: 10000000, modality: "Multimodal (Vision)", provider: "cloudflare", providerDisplay: "Cloudflare AI", providerUrl: "https://developers.cloudflare.com/workers-ai", modelUrl: "https://developers.cloudflare.com/workers-ai/models/", source: "cloudflare", requiresKey: true, signupUrl: "https://dash.cloudflare.com", rateLimits: "10K neurons/day (shared)", createdAt: 0 },
  { id: "cloudflare/@cf/mistralai/mistral-small-3.1-24b-instruct", name: "Mistral Small 3.1 24B", description: "Mistral Small 3.1 at the edge. 128K context with vision support.", contextLength: 131072, modality: "Multimodal (Vision)", provider: "cloudflare", providerDisplay: "Cloudflare AI", providerUrl: "https://developers.cloudflare.com/workers-ai", modelUrl: "https://developers.cloudflare.com/workers-ai/models/", source: "cloudflare", requiresKey: true, signupUrl: "https://dash.cloudflare.com", rateLimits: "10K neurons/day (shared)", createdAt: 0 },
  { id: "cloudflare/@cf/google/gemma-4-26b-a4b-it", name: "Gemma 4 26B (A4B)", description: "Google's Gemma 4 sparse MoE at 26B total / 4B active on Cloudflare's edge.", contextLength: 262144, modality: "Text", provider: "cloudflare", providerDisplay: "Cloudflare AI", providerUrl: "https://developers.cloudflare.com/workers-ai", modelUrl: "https://developers.cloudflare.com/workers-ai/models/", source: "cloudflare", requiresKey: true, signupUrl: "https://dash.cloudflare.com", rateLimits: "10K neurons/day (shared)", createdAt: 0 },
  { id: "cloudflare/@cf/moonshotai/kimi-k2.5", name: "Kimi K2.5", description: "Moonshot AI's Kimi K2.5 with 256K context and vision support on Cloudflare.", contextLength: 262144, modality: "Multimodal (Vision)", provider: "cloudflare", providerDisplay: "Cloudflare AI", providerUrl: "https://developers.cloudflare.com/workers-ai", modelUrl: "https://developers.cloudflare.com/workers-ai/models/", source: "cloudflare", requiresKey: true, signupUrl: "https://dash.cloudflare.com", rateLimits: "10K neurons/day (shared)", createdAt: 0 },
  { id: "cloudflare/@cf/deepseek-ai/deepseek-r1-distill-qwen-32b", name: "DeepSeek R1 Distill Qwen 32B", description: "DeepSeek R1 reasoning distilled into Qwen 32B. 32K context.", contextLength: 32768, modality: "Text", provider: "cloudflare", providerDisplay: "Cloudflare AI", providerUrl: "https://developers.cloudflare.com/workers-ai", modelUrl: "https://developers.cloudflare.com/workers-ai/models/", source: "cloudflare", requiresKey: true, signupUrl: "https://dash.cloudflare.com", rateLimits: "10K neurons/day (shared)", createdAt: 0 },
  { id: "cloudflare/@cf/openai/gpt-oss-120b", name: "GPT-OSS 120B", description: "OpenAI's 120B open model deployed globally at Cloudflare's edge.", contextLength: 131072, modality: "Text", provider: "cloudflare", providerDisplay: "Cloudflare AI", providerUrl: "https://developers.cloudflare.com/workers-ai", modelUrl: "https://developers.cloudflare.com/workers-ai/models/", source: "cloudflare", requiresKey: true, signupUrl: "https://dash.cloudflare.com", rateLimits: "10K neurons/day (shared)", createdAt: 0 },
];

const huggingface: ModelEntry[] = [
  { id: "huggingface/meta-llama/Meta-Llama-3.1-8B-Instruct", name: "Llama 3.1 8B Instruct", description: "Meta's Llama 3.1 8B instruction-tuned model via HuggingFace Inference.", contextLength: 131072, modality: "Text", provider: "huggingface", providerDisplay: "HuggingFace", providerUrl: "https://huggingface.co", modelUrl: "https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct", source: "huggingface", requiresKey: true, signupUrl: "https://huggingface.co/join", rateLimits: "100K credits/month", notes: "Free users get 100K inference credits/month. Opted into data training.", createdAt: 0 },
  { id: "huggingface/mistralai/Mistral-7B-Instruct-v0.3", name: "Mistral 7B Instruct", description: "Mistral's 7B instruct model. Efficient and capable for general tasks.", contextLength: 32768, modality: "Text", provider: "huggingface", providerDisplay: "HuggingFace", providerUrl: "https://huggingface.co", modelUrl: "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3", source: "huggingface", requiresKey: true, signupUrl: "https://huggingface.co/join", rateLimits: "100K credits/month", notes: "Free users get 100K inference credits/month.", createdAt: 0 },
  { id: "huggingface/Qwen/Qwen2.5-7B-Instruct", name: "Qwen 2.5 7B Instruct", description: "Alibaba's Qwen 2.5 7B instruction-tuned. Strong coding and math.", contextLength: 131072, modality: "Text", provider: "huggingface", providerDisplay: "HuggingFace", providerUrl: "https://huggingface.co", modelUrl: "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct", source: "huggingface", requiresKey: true, signupUrl: "https://huggingface.co/join", rateLimits: "100K credits/month", notes: "Free users get 100K inference credits/month.", createdAt: 0 },
  { id: "huggingface/microsoft/Phi-3.5-mini-instruct", name: "Phi-3.5 Mini Instruct", description: "Microsoft's compact 3.8B Phi-3.5 Mini. High performance for its size.", contextLength: 131072, modality: "Text", provider: "huggingface", providerDisplay: "HuggingFace", providerUrl: "https://huggingface.co", modelUrl: "https://huggingface.co/microsoft/Phi-3.5-mini-instruct", source: "huggingface", requiresKey: true, signupUrl: "https://huggingface.co/join", rateLimits: "100K credits/month", notes: "Free users get 100K inference credits/month.", createdAt: 0 },
];

export const STATIC_MODELS: ModelEntry[] = [
  ...groq,
  ...google,
  ...cerebras,
  ...nvidia,
  ...github,
  ...mistral,
  ...cohere,
  ...cloudflare,
  ...huggingface,
];
